---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Run Tox tests
jobs:
  tox_test:
    name: Tox test
    steps:
      - uses: actions/checkout@v3
      - name: Run Tox tests
        id: test
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: python3-rpm
    strategy:
      matrix:
        tox_env:
          # sync with /tox.ini
          - py36
          - py37
          - py311
          - py312
          - py313

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
