---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Run Tox tests
jobs:
  tox_test:
    name: Tox test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Tox tests
        id: test
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: >
            asciidoc
            createrepo_c
            docbook-style-xsl
            git
            git
            git-annex
            libxslt
            python3-bugzilla
            python3-rpm
            rpm-build
            rpmdevtools
            rsync
            which
    strategy:
      matrix:
        tox_env:
          # sync with /tox.ini
          - py36
          - py39
          - py312
          - py313

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
