---
name: Lint Python issues

on:
  pull_request:
    branches: [master]

jobs:
  python-lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: VCS Diff Lint
        uses: fedora-copr/vcs-diff-lint-action@v1
